### ISSUE TITLE
List index out of range in simulate.py

### ISSUE THREAD

**Issue by jopineda** [cdarby/samovar#3]
Hi,

I hope you are doing well! I am trying to run the samovar pipeline and I get the following issue:

`Traceback (most recent call last):
  File "/u/jpineda/tools/samovar/pipeline/1.simulate/simulate.py", line 253, in <module>
    regions = readIntervalFile(args.varfile,simMode,hetMode,homMode)
  File "/u/jpineda/tools/samovar/pipeline/1.simulate/simulate.py", line 29, in readIntervalFile
    if len(region[3]) != 1 or len(region[4]) != 1 or "PASS" not in region[6] or ("0|1" not in region[9] and "1|0" not in region[9]):
IndexError: list index out of range
Traceback (most recent call last):
  File "/u/jpineda/tools/samovar/pipeline/1.simulate/simulate.py", line 253, in <module>
    regions = readIntervalFile(args.varfile,simMode,hetMode,homMode)
  File "/u/jpineda/tools/samovar/pipeline/1.simulate/simulate.py", line 35, in readIntervalFile
    if len(region[3]) != 1 or len(region[4]) != 1 or "PASS" not in region[6] or ("0|0" not in region[9] and "1|1" not in region[9]):
IndexError: list index out of range`

I would really appreciate any help on this. Thanks in advance!

**Comment by cdarby** [comment]
The VCF file appears to be formatted differently than the script expects. Can you isolate the offending line?
